FROM python:3.8-slim-buster

COPY requirements.txt /app/requirements.txt
COPY app.py /app/app.py
COPY data/ /app/data/
COPY assets /app/assets

WORKDIR /app

RUN pip3 install -r requirements.txt

EXPOSE 8000

CMD ["python3", "app.py"]